.TH "__init__.py" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__init__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserveur\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBserveur\&.__author__\fP = 'sidya'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
