.TH "/home/sidya/PycharmProjects/DNC/serveur/Log.py" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sidya/PycharmProjects/DNC/serveur/Log.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLog\&.bcolors\fP"
.br
.RI "\fIDefine constant color value for different level\&. \fP"
.ti -1c
.RI "class \fBLog\&.lvl\fP"
.br
.RI "\fIDefine constant value for level utils\&. \fP"
.ti -1c
.RI "class \fBLog\&.SingleLevelFilter\fP"
.br
.RI "\fIFilter for one level\&. \fP"
.ti -1c
.RI "class \fBLog\&.Log\fP"
.br
.RI "\fI\fBLog\fP Manager\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBLog\fP"
.br
.RI "\fIModule \fBLog\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
