.TH "Log" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log \- Module \fBLog\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbcolors\fP"
.br
.RI "\fIDefine constant color value for different level\&. \fP"
.ti -1c
.RI "class \fBLog\fP"
.br
.RI "\fI\fBLog\fP Manager\&. \fP"
.ti -1c
.RI "class \fBlvl\fP"
.br
.RI "\fIDefine constant value for level utils\&. \fP"
.ti -1c
.RI "class \fBSingleLevelFilter\fP"
.br
.RI "\fIFilter for one level\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Module \fBLog\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
