.TH "Log.bcolors" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log.bcolors \- Define constant color value for different level\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBDEBUG\fP = '\\033[94m '"
.br
.ti -1c
.RI "string \fBINFO\fP = ' \\033[95m '"
.br
.ti -1c
.RI "string \fBWARNING\fP = ' \\033[93m '"
.br
.ti -1c
.RI "string \fBFAIL\fP = ' \\033[91m '"
.br
.ti -1c
.RI "string \fBENDC\fP = ' \\033[0m '"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define constant color value for different level\&. 
.SH "Member Data Documentation"
.PP 
.SS "string Log\&.bcolors\&.DEBUG = '\\033[94m '\fC [static]\fP"

.SS "string Log\&.bcolors\&.ENDC = ' \\033[0m '\fC [static]\fP"

.SS "string Log\&.bcolors\&.FAIL = ' \\033[91m '\fC [static]\fP"

.SS "string Log\&.bcolors\&.INFO = ' \\033[95m '\fC [static]\fP"

.SS "string Log\&.bcolors\&.WARNING = ' \\033[93m '\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
