.TH "Log.SingleLevelFilter" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log.SingleLevelFilter \- Filter for one level\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Filter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBpasslevel\fP, \fBreject\fP)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fBfilter\fP (self, record)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpasslevel\fP"
.br
.ti -1c
.RI "\fBreject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filter for one level\&. 


.PP
.nf

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Log\&.SingleLevelFilter\&.__init__ ( self,  passlevel,  reject)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpasslevel\fP level to filter 
.br
\fIreject\fP true on reject state 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def Log\&.SingleLevelFilter\&.filter ( self,  record)"

.SH "Member Data Documentation"
.PP 
.SS "Log\&.SingleLevelFilter\&.passlevel"

.SS "Log\&.SingleLevelFilter\&.reject"


.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
