.TH "/home/sidya/PycharmProjects/DNC/serveur/README.md" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sidya/PycharmProjects/DNC/serveur/README.md \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
