.TH "/home/sidya/PycharmProjects/DNC/serveur/Server.py" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sidya/PycharmProjects/DNC/serveur/Server.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBServer\fP"
.br
.RI "\fIModule server\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBServer\&.main\fP ()"
.br
.RI "\fILoad Configuration and Start the \fBServer\fP\&. \fP"
.ti -1c
.RI "def \fBServer\&.handle_connection\fP (connection, client_address)"
.br
.RI "\fIHandle a connection from a client\&. \fP"
.ti -1c
.RI "def \fBServer\&.handle_request\fP (connection, data)"
.br
.RI "\fIHandle a request\&. \fP"
.ti -1c
.RI "def \fBServer\&.broadcast_message\fP (connection, message)"
.br
.RI "\fIBroadcast a message to all the users connected except to the sender of the request\&. \fP"
.ti -1c
.RI "def \fBServer\&.user_list_active\fP (connection)"
.br
.RI "\fISend the list of enable user\&. \fP"
.ti -1c
.RI "def \fBServer\&.user_list_away\fP (connection)"
.br
.RI "\fISend the list of disable user\&. \fP"
.ti -1c
.RI "def \fBServer\&.change_name\fP (connection, pseudo)"
.br
.RI "\fIChange the nickname of the user\&. \fP"
.ti -1c
.RI "def \fBServer\&.new_name\fP (connection, pseudo)"
.br
.RI "\fIAffect the nickname of the user for the first time\&. \fP"
.ti -1c
.RI "def \fBServer\&.ask_private_message\fP (connection, pseudo)"
.br
.RI "\fIAsk for a private discussion between the sender of the request and the pseudo\&. \fP"
.ti -1c
.RI "def \fBServer\&.accept_private_message\fP (connection, pseudo)"
.br
.RI "\fIAccept a private discussion\&. \fP"
.ti -1c
.RI "def \fBServer\&.reject_private_message\fP (connection, pseudo)"
.br
.RI "\fIReject a private discussion\&. \fP"
.ti -1c
.RI "def \fBServer\&.private_message\fP (connection, pseudo, msg)"
.br
.RI "\fISend a private message if a private discussion had been accepted\&. \fP"
.ti -1c
.RI "def \fBServer\&.ask_file\fP (connection, pseudo, file)"
.br
.RI "\fIAsk for a file transfer between the sender of the request and the pseudo\&. \fP"
.ti -1c
.RI "def \fBServer\&.accept_file\fP (connection, pseudo, file, port)"
.br
.RI "\fIAccept a file transfer\&. \fP"
.ti -1c
.RI "def \fBServer\&.reject_file\fP (connection, pseudo, file)"
.br
.RI "\fIReject a file transfer\&. \fP"
.ti -1c
.RI "def \fBServer\&.enable_user\fP (connection)"
.br
.RI "\fIEnable user\&. \fP"
.ti -1c
.RI "def \fBServer\&.disable_user\fP (connection)"
.br
.RI "\fIDisable user\&. \fP"
.ti -1c
.RI "def \fBServer\&.quit_user\fP (connection)"
.br
.RI "\fIDisconnect user\&. \fP"
.ti -1c
.RI "def \fBServer\&.get_connection_by_pseudo\fP (pseudo)"
.br
.RI "\fIGet the socket descriptor by a pseudo\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBServer\&.USERLIST_ENABLE\fP = 300"
.br
.ti -1c
.RI "int \fBServer\&.USERLIST_DISABLE\fP = 301"
.br
.ti -1c
.RI "int \fBServer\&.HAS_JOIN\fP = 302"
.br
.ti -1c
.RI "int \fBServer\&.HAS_LEFT\fP = 303"
.br
.ti -1c
.RI "int \fBServer\&.NEW_MSG\fP = 304"
.br
.ti -1c
.RI "int \fBServer\&.NAME_CHANGED\fP = 305"
.br
.ti -1c
.RI "int \fBServer\&.NEW_PM\fP = 306"
.br
.ti -1c
.RI "int \fBServer\&.ASKING_FOR_PM\fP = 307"
.br
.ti -1c
.RI "int \fBServer\&.PRIVATE_DISCU_ACCEPTED_FROM\fP = 308"
.br
.ti -1c
.RI "int \fBServer\&.PRIVATE_DISCU_REFUSED_FROM\fP = 309"
.br
.ti -1c
.RI "int \fBServer\&.IS_NOW_ENABLE\fP = 310"
.br
.ti -1c
.RI "int \fBServer\&.IS_NOW_DISABLE\fP = 311"
.br
.ti -1c
.RI "int \fBServer\&.HAS_ASKED_FILE\fP = 312"
.br
.ti -1c
.RI "int \fBServer\&.CAN_SEND_FILE\fP = 313"
.br
.ti -1c
.RI "int \fBServer\&.HAS_REJECT_FILE\fP = 314"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_CHANNEL_JOINED\fP = 200"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_CHANNEL_QUIT\fP = 201"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_MESSAGE_SENDED\fP = 202"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_NICKNAME_CHANGED\fP = 203"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_PM_SENDED\fP = 205"
.br
.ti -1c
.RI "int \fBServer\&.SUCCESSFUL_ASKED_CONV\fP = 206"
.br
.ti -1c
.RI "int \fBServer\&.SUCCESSFUL_ACCEPTED_CONV\fP = 207"
.br
.ti -1c
.RI "int \fBServer\&.SUCCESSFUL_REFUSED_CONV\fP = 208"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_ENABLED\fP = 209"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_DISABLED\fP = 210"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_PMFILE\fP = 211"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_ACCEPTED_FILE\fP = 212"
.br
.ti -1c
.RI "int \fBServer\&.SUCC_REFUSED_FILE\fP = 213"
.br
.ti -1c
.RI "int \fBServer\&.ERR_NICKNAME_ALREADY_USED\fP = 400"
.br
.ti -1c
.RI "int \fBServer\&.ERR_NO_NICKNAME\fP = 401"
.br
.ti -1c
.RI "int \fBServer\&.ERR_CONV_NOT_ALLOWED\fP = 402"
.br
.ti -1c
.RI "int \fBServer\&.DEST_NOT_FOUND\fP = 403"
.br
.ti -1c
.RI "int \fBServer\&.ERR_ALREADY_ASKED_FOR_PM\fP = 404"
.br
.ti -1c
.RI "int \fBServer\&.ERR_NO_INVIT_TO_CONV_FOUND\fP = 405"
.br
.ti -1c
.RI "int \fBServer\&.ERR_UNKNOWN_ACCEPTED_FILE\fP = 406"
.br
.ti -1c
.RI "int \fBServer\&.COMMAND_NOT_FOUND\fP = 407"
.br
.ti -1c
.RI "int \fBServer\&.ERR_INVALID_NICKNAME\fP = 408"
.br
.ti -1c
.RI "int \fBServer\&.ERR_INTERNAL_SERVER_ERROR\fP = 409"
.br
.ti -1c
.RI "int \fBServer\&.ERR_NOT_DISABLED\fP = 410"
.br
.ti -1c
.RI "int \fBServer\&.ERR_NOT_ENABLED\fP = 411"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
