.TH "serveur.Log.Log" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serveur.Log.Log \- \fBLog\fP Manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, directory)"
.br
.RI "\fIDefine 3 differents utils : activity\&.log -> all activity warning\&.log -> only warning error\&.log -> error Write all message on terminal too\&. \fP"
.ti -1c
.RI "def \fBprintL\fP (self, pMsg, pLvl)"
.br
.RI "\fIAdd color and write in log with an define level\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlogger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLog\fP Manager\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def serveur\&.Log\&.Log\&.__init__ ( self,  directory)"

.PP
Define 3 differents utils : activity\&.log -> all activity warning\&.log -> only warning error\&.log -> error Write all message on terminal too\&. 
.SH "Member Function Documentation"
.PP 
.SS "def serveur\&.Log\&.Log\&.printL ( self,  pMsg,  pLvl)"

.PP
Add color and write in log with an define level\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpMsg\fP message to write in log 
.br
\fIpLvl\fP level of log message 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "serveur\&.Log\&.Log\&.logger"


.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
