.TH "serveur.Log.lvl" 3 "Wed Apr 15 2015" "Version 1.0" "Server DNC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serveur.Log.lvl \- Define constant value for level utils\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNOTSET\fP = 0"
.br
.ti -1c
.RI "int \fBDEBUG\fP = 10"
.br
.ti -1c
.RI "int \fBINFO\fP = 20"
.br
.ti -1c
.RI "int \fBWARNING\fP = 30"
.br
.ti -1c
.RI "int \fBFAIL\fP = 40"
.br
.ti -1c
.RI "int \fBCRITICAL\fP = 50"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define constant value for level utils\&. 
.SH "Field Documentation"
.PP 
.SS "int serveur\&.Log\&.lvl\&.CRITICAL = 50\fC [static]\fP"

.SS "int serveur\&.Log\&.lvl\&.DEBUG = 10\fC [static]\fP"

.SS "int serveur\&.Log\&.lvl\&.FAIL = 40\fC [static]\fP"

.SS "int serveur\&.Log\&.lvl\&.INFO = 20\fC [static]\fP"

.SS "int serveur\&.Log\&.lvl\&.NOTSET = 0\fC [static]\fP"

.SS "int serveur\&.Log\&.lvl\&.WARNING = 30\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Server DNC from the source code\&.
